package com.example.otavio.techwords.BancoSQLite;

import android.app.Activity;

import com.example.otavio.techwords.Model.Disciplina;
import com.example.otavio.techwords.Model.Palavra;

public class DadosIniciais extends Activity {

    private BancoPalavras crud;
    private BancoDisciplinas banco;
    private BancoStatus bancoStatus;

    public void insereDados() {
        crud = new BancoPalavras(this);
        banco = new BancoDisciplinas(this);
        bancoStatus = new BancoStatus(this);

        System.out.println("INSERINDO DISCIPLINAS");
        Disciplina disciplina0 = new Disciplina(1, "Banco de Dados");
        System.out.println(banco.insereDado(disciplina0));
        Disciplina disciplina1 = new Disciplina(2, "Informática Básica");
        System.out.println(banco.insereDado(disciplina1));
        Disciplina disciplina2 = new Disciplina(3, "Inglês Técnico");
        System.out.println(banco.insereDado(disciplina2));
        Disciplina disciplina3 = new Disciplina(4, "Manutenção de Comp.");
        System.out.println(banco.insereDado(disciplina3));
        Disciplina disciplina4 = new Disciplina(5, "Organização de Comp.");
        System.out.println(banco.insereDado(disciplina4));
        Disciplina disciplina5 = new Disciplina(6, "Programação");
        System.out.println(banco.insereDado(disciplina5));
        Disciplina disciplina6 = new Disciplina(7, "Redes de Comp.");
        System.out.println(banco.insereDado(disciplina6));
        Disciplina disciplina7 = new Disciplina(8, "Web");
        System.out.println(banco.insereDado(disciplina7));

        Palavra palavra0 = new Palavra(1, "User", "Usuário", "Utilizador.", "Pessoa que faz uso do computador, de programas, sistemas ou serviços informáticos.", "2");
        System.out.println(crud.insereDado(palavra0));
        Palavra palavra1 = new Palavra(2, "Undo", "Desfazer", "Desmanchar /  Despedaçar.", "Destruir o que está feito.", "2");
        System.out.println(crud.insereDado(palavra1));
        Palavra palavra2 = new Palavra(3, "Underline", "Sublinhar", "Marcar /  Realçar.", "Traçar linha ou linhas por baixo de uma ou mais palavras.", "2");
        System.out.println(crud.insereDado(palavra2));
        Palavra palavra3 = new Palavra(4, "Type", "Digitar", "Teclar.", "Introduzir (texto ou informação) com os dedos através de um teclado.", "2");
        System.out.println(crud.insereDado(palavra3));
        Palavra palavra4 = new Palavra(5, "Size", "Tamanho", "Grandeza /  Medida.", "Grandeza, volume, dimensões de um corpo ou objeto.", "2");
        System.out.println(crud.insereDado(palavra4));
        Palavra palavra5 = new Palavra(6, "Send", "Enviar", "Mandar.", "Remeter, mandar.", "2");
        System.out.println(crud.insereDado(palavra5));
        Palavra palavra6 = new Palavra(7, "Select", "Selecionar", "Escolher.", "Fazer a seleção de /  Marcar as opções pretendidas.", "2");
        System.out.println(crud.insereDado(palavra6));
        Palavra palavra7 = new Palavra(8, "Save", "Salvar", "Gravar /  Guardar.", "Registar dados.", "2");
        System.out.println(crud.insereDado(palavra7));
        Palavra palavra8 = new Palavra(9, "Screen", "Tela", "Painel.", "Superfície, geralmente branca, na qual se projectam vistas fixas ou animadas.", "2");
        System.out.println(crud.insereDado(palavra8));
        Palavra palavra9 = new Palavra(10, "Search", "Pesquisar", "Procurar.", "Indagar, investigar, procurar.", "2");
        System.out.println(crud.insereDado(palavra9));
        Palavra palavra10 = new Palavra(11, "Search", "Relatar", "Descrever.", "Fazer o relatório.", "2");
        System.out.println(crud.insereDado(palavra10));
        Palavra palavra11 = new Palavra(12, "Return", "Retornar", "Regressar /  Voltar.", "Voltar ao ponto de onde partiu.", "2");
        System.out.println(crud.insereDado(palavra11));
        Palavra palavra12 = new Palavra(13, "Register", "Registrar", "Gravar.", "Inscrever no registo.", "2");
        System.out.println(crud.insereDado(palavra12));
        Palavra palavra13 = new Palavra(14, "Print", "Imprimir", " ", "Transferir para um papel caracteres ou desenhos.", "2");
        System.out.println(crud.insereDado(palavra13));
        Palavra palavra14 = new Palavra(15, "Password", "Senha", "Palavra-Chave.", "Conjunto de caracteres que identifica o usuário e permite o acesso a programas e dados, indisponíveis ao público.", "2");
        System.out.println(crud.insereDado(palavra14));
        Palavra palavra15 = new Palavra(16, "Page", "Página", "Lauda /  Folha.", "Cada um dos lados de uma folha de papel.", "2");
        System.out.println(crud.insereDado(palavra15));
        Palavra palavra16 = new Palavra(17, "Open", "Abrir", "Iniciar.", "Dar algo por aberto ou iniciado.", "2");
        System.out.println(crud.insereDado(palavra16));
        Palavra palavra17 = new Palavra(18, "Option", "Opção", "Escolha /  Seleção /  Alternativa.", "Faculdade, ação de optar, de escolher entre duas ou várias coisas.", "2");
        System.out.println(crud.insereDado(palavra17));
        Palavra palavra18 = new Palavra(19, "New", "Novo", "Atual /  Recente /  Moderno.", "Que existe há pouco tempo /  que apareceu recentemente.", "2");
        System.out.println(crud.insereDado(palavra18));
        Palavra palavra19 = new Palavra(20, "Log in", "Entrar", "Ingressar /  Adentrar.", "Passar para dentro /  introduzir-se / iniciar.", "2");
        System.out.println(crud.insereDado(palavra19));
        Palavra palavra20 = new Palavra(21, "Log out", "Sair", "Deixar /  Largar.", "Passar de dentro para fora /  retirar-se /  ausentar-se /  escapar.", "2");
        System.out.println(crud.insereDado(palavra20));
        Palavra palavra21 = new Palavra(22, "Power", "Ligar", "Unir /  Juntar.", "Estabelecer uma conexão ou comunicação.", "2");
        System.out.println(crud.insereDado(palavra21));
        Palavra palavra22 = new Palavra(23, "Header", "Cabeçalho", "Título.", "O título, vinhetas e dizeres que formam a parte superior da primeira página de um jornal.", "2");
        System.out.println(crud.insereDado(palavra22));
        Palavra palavra23 = new Palavra(24, "Icon", "Ícone", "Imagem.", "Símbolo ou imagem gráfica que, ao clicar, aciona um programa, ferramenta etc.", "2");
        System.out.println(crud.insereDado(palavra23));
        Palavra palavra24 = new Palavra(25, "Record", "Gravar", "Registrar /  Salvar.", "Gravar na memória.", "2");
        System.out.println(crud.insereDado(palavra24));
        Palavra palavra25 = new Palavra(26, "Paste", "Colar", "Grudar /  Pregar.", "Inserir, em um arquivo, texto ou gráficos que foram copiados ou removidos de outro arquivo ou, ainda, de uma parte para outra do mesmo arquivo.", "2");
        System.out.println(crud.insereDado(palavra25));
        Palavra palavra26 = new Palavra(27, "Software", "Software", "Aplicativo /  Programa.", "Conjunto de componentes lógicos de um computador ou sistema de processamento de dados /  programa, rotina ou conjunto de instruções que controlam o funcionamento de um computador.", "5");
        System.out.println(crud.insereDado(palavra26));
        Palavra palavra27 = new Palavra(28, "Hardware", "Hardware", " ", "Conjunto dos componentes físicos (material eletrônico, placas, monitor, equipamentos periféricos etc.) de um computador.", "5");
        System.out.println(crud.insereDado(palavra27));
        Palavra palavra28 = new Palavra(29, "Add", "Adicionar", "Somar /  Acrescer /  Acrescentar.", "Acrescentar uma coisa a outra /  juntar.", "5");
        System.out.println(crud.insereDado(palavra28));
        Palavra palavra29 = new Palavra(30, "Allow", "Permitir", "Autorizar /  Conceder.", "Dar permissão ou licença para /  conceder, consentir.", "5");
        System.out.println(crud.insereDado(palavra29));
        Palavra palavra30 = new Palavra(31, "Deny", "Negar", "Proibir.", "Não permitir /  Recusar o que foi pedido ou desejado.", "5");
        System.out.println(crud.insereDado(palavra30));
        Palavra palavra31 = new Palavra(32, "Application", "Aplicativo", "Programa.", "Tipo de software concebido para desempenhar tarefas práticas para que o usuário do computador possa realizar determinados trabalhos.", "5");
        System.out.println(crud.insereDado(palavra31));
        Palavra palavra32 = new Palavra(33, "Arrow", "Seta", "Ponteiro.", "Objeto com a forma de uma flecha.", "5");
        System.out.println(crud.insereDado(palavra32));
        Palavra palavra33 = new Palavra(34, "Bold", "Negrito", "Gordo /  Preto.", "Diz-se de ou tipo mais grosso que o comum, usado no texto para pôr em destaque alguma parte dele.", "5");
        System.out.println(crud.insereDado(palavra33));
        Palavra palavra34 = new Palavra(35, "Bug", "Erro", "Falha /  Defeito.", "Ação Inadequada.", "5");
        System.out.println(crud.insereDado(palavra34));
        Palavra palavra35 = new Palavra(36, "Clipboard", "Área de Transferência", " ", "Recurso utilizado por um sistema operacional para o armazenamento de pequenas quantidades de dados para transferênciaentre documentos ou aplicativos, através das operações de cortar, copiar e colar.", "5");
        System.out.println(crud.insereDado(palavra35));
        Palavra palavra36 = new Palavra(37, "Copyright", "Direitos Autorais", " ", "Direitos que garantem a artistas e divulgadores instrumentos para recuperar o capital investido, além de assegurar o respeito à autoria das obras.", "5");
        System.out.println(crud.insereDado(palavra36));
        Palavra palavra37 = new Palavra(38, "Data", "Dados", "Informação /  Fato.", "Expressões gerais que descrevem características /  informações menos elaboradas.", "5");
        System.out.println(crud.insereDado(palavra37));
        Palavra palavra38 = new Palavra(39, "Delete", "Deletar", "Cancelar /  Suprimir.", "Apagar texto, arquivo, documento.", "5");
        System.out.println(crud.insereDado(palavra38));
        Palavra palavra39 = new Palavra(40, "Developer", "Desenvolver", "Evoluir /  Crescer.", "Fazer passar por um processo de crescimento, de evolução por alterações sucessivas, de um estágio menos perfeito a um mais perfeito ou mais altamente organizado.", "5");
        System.out.println(crud.insereDado(palavra39));
        Palavra palavra40 = new Palavra(41, "Desktop", "Área de Trabalho", " ", "Principal área exibida na tela quando se liga o computador e faz logon no Windows. É onde se exibe tudo o que é aberto (programas, pastas, arquivos) e que também organiza as atividades.", "5");
        System.out.println(crud.insereDado(palavra40));
        Palavra palavra41 = new Palavra(42, "Display", "Visor", "Ecrã.", "Hardware responsável por levar as informações visuais ao indivíduo.", "5");
        System.out.println(crud.insereDado(palavra41));
        Palavra palavra42 = new Palavra(43, "Enable", "Habilitar", "Aprovar.", "Ativar rotina, entrada de menu ou dispositivo e fazer com que exerça suas funções.", "5");
        System.out.println(crud.insereDado(palavra42));
        Palavra palavra43 = new Palavra(44, "Execute", "Executar", "Realizar.", "Fazer funcionar um programa ou um processo de computador /  rodar.", "5");
        System.out.println(crud.insereDado(palavra43));
        Palavra palavra44 = new Palavra(45, "File", "Arquivo", "Registro /  Acervo.", "Seção de dados de um computador, como lista de endereços, textos, contas de clientes etc., em forma de registros individuais que podem conter dados, caracteres, dígitos ou gráficos.", "5");
        System.out.println(crud.insereDado(palavra44));
        Palavra palavra45 = new Palavra(46, "Accept", "Aceitar", "Concordar.", "Estar de acordo /  aprovar.", "5");
        System.out.println(crud.insereDado(palavra45));
        Palavra palavra46 = new Palavra(47, "Large", "Largo", "Extenso.", "Que é abundante ou considerável /  numeroso, vasto.", "5");
        System.out.println(crud.insereDado(palavra46));
        Palavra palavra47 = new Palavra(48, "Layout", "Forma", "Formato.", "Estado físico como algo se apresenta /  por exemplo, um corpo ou uma substância.", "5");
        System.out.println(crud.insereDado(palavra47));
        Palavra palavra48 = new Palavra(49, "Leak", "Vazar", "Soltar.", "Vir a público (certa informação) em consequência de descuido, investigação, engano, indiscrição etc.", "5");
        System.out.println(crud.insereDado(palavra48));
        Palavra palavra49 = new Palavra(50, "Upgrade", "Atualizar", "Modernizar /  Melhorar.", " Fazer atualização (cultural, econômica, tecnológica etc.) de algo", "5");
        System.out.println(crud.insereDado(palavra49));
        Palavra palavra50 = new Palavra(51, "Update", "Atualizar", "Modernizar /  Melhorar.", "Tornar(-se) atual /  adequar(-se) às novas características do momento presente /  modernizar(-se).", "5");
        System.out.println(crud.insereDado(palavra50));
        Palavra palavra51 = new Palavra(52, "Benchmark", "Comparativo", " ", "Relativo a, que envolve, estabelece ou emprega comparação.", "5");
        System.out.println(crud.insereDado(palavra51));
        Palavra palavra52 = new Palavra(53, "Format", "Formato", "Configuração /  Padrão.", "Configuração exterior de uma pessoa ou de alguma coisa /  forma.", "5");
        System.out.println(crud.insereDado(palavra52));
        Palavra palavra53 = new Palavra(54, "Checkup", "Checar", "Verificar /  Analisar.", "Conferir a exatidão de fatos, de números etc.", "5");
        System.out.println(crud.insereDado(palavra53));
        Palavra palavra54 = new Palavra(55, "What", "O quê", " ", " ", "3");
        System.out.println(crud.insereDado(palavra54));
        Palavra palavra55 = new Palavra(56, "Why", "Por que", " ", " ", "3");
        System.out.println(crud.insereDado(palavra55));
        Palavra palavra56 = new Palavra(57, "The", "O", " ", " ", "3");
        System.out.println(crud.insereDado(palavra56));
        Palavra palavra57 = new Palavra(58, "A / an", "Um/uma", " ", "Designa pessoa, animal ou algo ainda não mencionado ou identificado no texto ou no diálogo.", "3");
        System.out.println(crud.insereDado(palavra57));
        Palavra palavra58 = new Palavra(59, "This/those", "Esse/esses", " ", "Designa pessoa ou coisa que se acham afastados do emissor e perto do receptor.", "3");
        System.out.println(crud.insereDado(palavra58));
        Palavra palavra59 = new Palavra(60, "When", "Quando", " ", "Expressa circunstância de tempo /  em que ocasião.", "3");
        System.out.println(crud.insereDado(palavra59));
        Palavra palavra60 = new Palavra(61, "And", "E", " ", " ", "3");
        System.out.println(crud.insereDado(palavra60));
        Palavra palavra61 = new Palavra(62, "Or", "Ou", " ", "Indica alternância ou exclusão.", "3");
        System.out.println(crud.insereDado(palavra61));
        Palavra palavra62 = new Palavra(63, "If", "Se", " ", " ", "3");
        System.out.println(crud.insereDado(palavra62));
        Palavra palavra63 = new Palavra(64, "Else", "Senão", " ", "De outro modo.", "3");
        System.out.println(crud.insereDado(palavra63));
        Palavra palavra64 = new Palavra(65, "Do", "Fazer", " ", "Produzir através de determinada ação.", "3");
        System.out.println(crud.insereDado(palavra64));
        Palavra palavra65 = new Palavra(66, "Close", "Fechar", " ", "Encerrar ou cessar, provisoriamente ou em definitivo.", "3");
        System.out.println(crud.insereDado(palavra65));
        Palavra palavra66 = new Palavra(67, "Open", "Abrir", "Iniciar.", "Começar a funcionar /  Fazer funcionar.", "3");
        System.out.println(crud.insereDado(palavra66));
        Palavra palavra67 = new Palavra(68, "Export", "Exportar", "Levar para fora.", "Alterar um formato de arquivo de dados gerado pelo aplicativo utilizado pelo usuário, possibilitando que seja aberto e editado por outro aplicativo.", "3");
        System.out.println(crud.insereDado(palavra67));
        Palavra palavra68 = new Palavra(69, "Import", "Importar", "Trazer.", "Trazer alguma coisa de fora de um sistema.", "3");
        System.out.println(crud.insereDado(palavra68));
        Palavra palavra69 = new Palavra(70, "Check", "Checar", "Verificar", "Conferir a exatidão de fatos.", "3");
        System.out.println(crud.insereDado(palavra69));
        Palavra palavra70 = new Palavra(71, "Wait", "Esperar", "Aguardar.", "Não agir, não tomar decisões, não desistir de algo, até a efetuação de um evento que se tem por certo, ou provável, ou desejável.", "3");
        System.out.println(crud.insereDado(palavra70));
        Palavra palavra71 = new Palavra(72, "Search", "Pesquisar", "Buscar.", "Obter informações acerca de algo.", "3");
        System.out.println(crud.insereDado(palavra71));
        Palavra palavra72 = new Palavra(73, "Tools", "Ferramentas", "Acessórios.", "São opções que podem ser utilizadas pelo usuário de um computador com o objetivo de facilitar a execução de alguma tarefa.", "3");
        System.out.println(crud.insereDado(palavra72));
        Palavra palavra73 = new Palavra(74, "Help", "Ajuda", "Amparo /  Assistência.", "Ação de auxiliar, de socorrer", "3");
        System.out.println(crud.insereDado(palavra73));
        Palavra palavra74 = new Palavra(75, "Word", "Palavra", "Termo /  Vocábulo.", "Unidade pertencente a uma das grandes classes gramaticais, como substantivo, verbo, adjetivo etc.", "3");
        System.out.println(crud.insereDado(palavra74));
        Palavra palavra75 = new Palavra(76, "Article", "Artigo", "Texto /  Reportagem.", "Texto jornalístico (pode também integrar outras publicações, como revistas, livros e edições especiais) assinado pelo autor, cujo objetivo é emitir uma opinião, comentar um ponto de vista, debater um assunto etc.", "3");
        System.out.println(crud.insereDado(palavra75));
        Palavra palavra76 = new Palavra(77, "Run", "Rodar", "Funcionar.", "Fazer funcionar um programa.", "3");
        System.out.println(crud.insereDado(palavra76));
        Palavra palavra77 = new Palavra(78, "Debug", "Depurar", "Apurar.", "Submeter o código de um programa a exame para detectar possíveis falhas e eliminá-las.", "3");
        System.out.println(crud.insereDado(palavra77));
        Palavra palavra78 = new Palavra(79, "Motherboard", "Placa-mãe", " ", "Placa principal de um computador, contendo diversos conectores e a unidade central de processamento /  placa lógica.", "4");
        System.out.println(crud.insereDado(palavra78));
        Palavra palavra79 = new Palavra(80, "Printer", "Impressora", " ", "Periférico do computador que imprime, em papel, textos ou imagens gerados por computador.", "4");
        System.out.println(crud.insereDado(palavra79));
        Palavra palavra80 = new Palavra(81, "Hard disk (hd)", "Disco rígido", " ", "Hardware responsável pelo armazenamento de dados.", "4");
        System.out.println(crud.insereDado(palavra80));
        Palavra palavra81 = new Palavra(82, "Setup", "Configurar", "Ajustar.", "Dar ou tornar determinado aspecto, forma ou figura.", "4");
        System.out.println(crud.insereDado(palavra81));
        Palavra palavra82 = new Palavra(83, "Backup", "Cópia de Segurança", " ", "Cópia de dados de um dispositivo de armazenamento a outro para que possam ser restaurados em caso da perda dos dados originais, o que pode envolver apagamentos acidentais ou corrupção de dados.", "4");
        System.out.println(crud.insereDado(palavra82));
        Palavra palavra83 = new Palavra(84, "Operational system", "Sistema operacional", " ", "Software mais importante que é executado em um computador, é ele quem dá a possibilidade de usarmos e dar ordens ao mesmo. ", "4");
        System.out.println(crud.insereDado(palavra83));
        Palavra palavra84 = new Palavra(85, "Slot", "Compartimento", "Repartição.", "Cada uma das divisões ou repartições de certa área.", "4");
        System.out.println(crud.insereDado(palavra84));
        Palavra palavra85 = new Palavra(86, "Display", "Tela/Monitor", "Painel.", "Periférico que exibe visualmente numa tela as informações (textos ou imagens) originadas pelo computador.", "4");
        System.out.println(crud.insereDado(palavra85));
        Palavra palavra86 = new Palavra(87, "No-break", "Nobreak", " ", "Dispositivo alimentado a bateria, capaz de fornecer energia elétrica a um sistema por um certo tempo, em situações de emergência, no caso de interrupção do fornecimento de energia da rede pública.", "4");
        System.out.println(crud.insereDado(palavra86));
        Palavra palavra87 = new Palavra(88, "Touchpad", "Touchpad", " ", "É o dispositivo sensível ao toque encontrado vastamente em notebooks responsável por cumprir a função do mouse.", "4");
        System.out.println(crud.insereDado(palavra87));
        Palavra palavra88 = new Palavra(89, "Touchscreen", "Sensível ao Toque", " ", "Consiste numa tecnologia que permite a interação e comando direto e intuitivo de determinado dispositivo eletrônico através do toque.", "4");
        System.out.println(crud.insereDado(palavra88));
        Palavra palavra89 = new Palavra(90, "Clock", "Relógio", " ", "Circuito que gera pulsos usados para sincronizar o equipamento.", "4");
        System.out.println(crud.insereDado(palavra89));
        Palavra palavra90 = new Palavra(91, "Onboard", "Na placa-mãe", " ", "Componente que se encontra integrado à placa mãe.", "4");
        System.out.println(crud.insereDado(palavra90));
        Palavra palavra91 = new Palavra(92, "Offboard", "Fora da placa-mãe", " ", "Componente não integrado à placa mãe.", "4");
        System.out.println(crud.insereDado(palavra91));
        Palavra palavra92 = new Palavra(93, "Cable", "Cabo", "Fio.", "Condutor utilizado para transmissão de sinais.", "4");
        System.out.println(crud.insereDado(palavra92));
        Palavra palavra93 = new Palavra(94, "Machine", "Máquina", "Aparelho /  Equipamento.", "Qualquer equipamento empregado com um fim específico e cuja ação mecânica é capaz de substituir o trabalho humano.", "4");
        System.out.println(crud.insereDado(palavra93));
        Palavra palavra94 = new Palavra(95, "Memory", "Memória", " ", "Conjunto de chips num computador para armazenar dados e programas.", "4");
        System.out.println(crud.insereDado(palavra94));
        Palavra palavra95 = new Palavra(96, "Instruction", "Instrução", "Explicação /  Esclarecimento.", "Código que determina a operação a ser executada.", "4");
        System.out.println(crud.insereDado(palavra95));
        Palavra palavra96 = new Palavra(97, "Keyboard", "Teclado", " ", "Conjunto de teclas com as quais se operam computador, máquina de escrever, calculadora ou aparelho semelhante.", "4");
        System.out.println(crud.insereDado(palavra96));
        Palavra palavra97 = new Palavra(98, "Personal computer", "Computador pessoal (pc)", " ", "Máquina destinada ao recebimento, armazenamento e/ou processamento de dados, em pequena ou grande escala, de forma rápida, conforme um programa específico /  computador eletrônico.", "4");
        System.out.println(crud.insereDado(palavra97));
        Palavra palavra98 = new Palavra(99, "Processor", "Processador", " ", "Componente central de um computador, provido de um circuito integrado com capacidade para realizar o processamento de dados, de acordo com instruções predeterminadas.", "4");
        System.out.println(crud.insereDado(palavra98));
        Palavra palavra99 = new Palavra(100, "Storage", "Armazenamento", " ", "Ato de armazenar dados, informações.", "4");
        System.out.println(crud.insereDado(palavra99));
        Palavra palavra100 = new Palavra(101, "Remove", "Remover", "Tirar /  Eliminar.", "Suprimir dados ou arquivos desnecessários /  eliminar.", "4");
        System.out.println(crud.insereDado(palavra100));
        Palavra palavra101 = new Palavra(102, "Version", "Versão", "Variante.", "Cada uma das etapas que um programa de computador precisa para sua elaboração e desenvolvimento.", "4");
        System.out.println(crud.insereDado(palavra101));
        Palavra palavra102 = new Palavra(103, "Process", "Processo", "Progresso.", "Método empregado para se fazer alguma coisa /  maneira, procedimento.", "4");
        System.out.println(crud.insereDado(palavra102));
        Palavra palavra103 = new Palavra(104, "Cancel", "Cancelar", "Eliminar /  Excluir.", "Suspender a realização de algo que se havia planejado.", "4");
        System.out.println(crud.insereDado(palavra103));
        Palavra palavra104 = new Palavra(105, "Clear", "Limpar", "Apagar.", "Remover dados desnecessários ou desatualizados de um arquivo ou disco.", "6");
        System.out.println(crud.insereDado(palavra104));
        Palavra palavra105 = new Palavra(106, "Select", "Selecionar", "Escolher.", "Escolher informações específicas de um banco de dados /  Destacar uma parte de um documento ou de um arquivo.", "6");
        System.out.println(crud.insereDado(palavra105));
        Palavra palavra106 = new Palavra(107, "Break", "Parar", "Interromper.", "Interromper, de maneira provisória ou definitiva, ação ou operação que se estava fazendo.", "6");
        System.out.println(crud.insereDado(palavra106));
        Palavra palavra107 = new Palavra(108, "While", "Enquanto", "Durante.", "Ao mesmo tempo que.", "6");
        System.out.println(crud.insereDado(palavra107));
        Palavra palavra108 = new Palavra(109, "Failure", "Falha", "Erro.", "Alteração ou interrupção de funcionamento normal.", "6");
        System.out.println(crud.insereDado(palavra108));
        Palavra palavra109 = new Palavra(110, "Success", "Sucesso", "Êxito.", "Bom resultado.", "6");
        System.out.println(crud.insereDado(palavra109));
        Palavra palavra110 = new Palavra(111, "Get", "Pegar", "Prender.", "Agarrar ou segurar algo.", "6");
        System.out.println(crud.insereDado(palavra110));
        Palavra palavra111 = new Palavra(112, "Print", "Escrever", "Descrever.", "Expressar-se por escrito.", "6");
        System.out.println(crud.insereDado(palavra111));
        Palavra palavra112 = new Palavra(113, "Long", "Longo", "Comprido.", "De grande extensão, no sentido longitudinal.", "6");
        System.out.println(crud.insereDado(palavra112));
        Palavra palavra113 = new Palavra(114, "Scan", "Ler", "Captar.", "Disponibilizar dados armazenados.", "6");
        System.out.println(crud.insereDado(palavra113));
        Palavra palavra114 = new Palavra(115, "Error", "Erro", "Defeito /  Falha.", "Desvio de uma regra de conduta estabelecida /  Ação inadequada.", "6");
        System.out.println(crud.insereDado(palavra114));
        Palavra palavra115 = new Palavra(116, "Include", "Incluir", "Juntar.", "Passar a fazer parte de um grupo ou de um todo.", "6");
        System.out.println(crud.insereDado(palavra115));
        Palavra palavra116 = new Palavra(117, "Structure", "Estrutura", "Organização.", "Organização e disposição das partes ou dos elementos essenciais que formam algo.", "6");
        System.out.println(crud.insereDado(palavra116));
        Palavra palavra117 = new Palavra(118, "Function", "Função", "Aplicação.", "O conjunto das ações e atividades atribuídas a, esperadas ou exigidas de uma pessoa ou de um grupo.", "6");
        System.out.println(crud.insereDado(palavra117));
        Palavra palavra118 = new Palavra(119, "Class", "Classe", " ", "Grupo de coisas com atributos semelhantes.", "6");
        System.out.println(crud.insereDado(palavra118));
        Palavra palavra119 = new Palavra(120, "Logical", "Lógico", "Coerente.", "Que é decorrente de um fato ou de um processo, como resultado ou efeito de determinadas condições.", "6");
        System.out.println(crud.insereDado(palavra119));
        Palavra palavra120 = new Palavra(121, "Case", "Caso", " ", "Aquilo que se torna, se tornou ou pode se tornar real no tempo e no espaço.", "6");
        System.out.println(crud.insereDado(palavra120));
        Palavra palavra121 = new Palavra(122, "Variable", "Variável", "Mutável /  Modificável.", "Espaço reservado na memória de um computador, capaz de armazenar um determinado tipo de dado que pode variar durante a execução do programa.", "6");
        System.out.println(crud.insereDado(palavra121));
        Palavra palavra122 = new Palavra(123, "Algorithm", "Algoritimo", " ", "Conjunto de regras e operações e procedimentos, definidos e ordenados usados na solução de um problema, ou de classe de problemas, em um número finito de etapas.", "6");
        System.out.println(crud.insereDado(palavra122));
        Palavra palavra123 = new Palavra(124, "Interface", "Interface", " ", "Parte de um programa que permite a transmissão de dados para um outro programa.", "6");
        System.out.println(crud.insereDado(palavra123));
        Palavra palavra124 = new Palavra(125, "Library", "Biblioteca", " ", "Coleção ordenada de código de programas disponíveis para consulta e utilização como subsídio na execução de outros programas.", "6");
        System.out.println(crud.insereDado(palavra124));
        Palavra palavra125 = new Palavra(126, "Language", "Linguagem", "Código.", "Linguagem de computador projetada para processar e expressar algoritmos.", "6");
        System.out.println(crud.insereDado(palavra125));
        Palavra palavra126 = new Palavra(127, "Object-oriented programming", "Programação Orientada à Objeto", " ", "É um modelo de análise, projeto e programação de sistemas de softwarebaseado na composição e interação entre diversas unidades de software chamadas de objetos.", "6");
        System.out.println(crud.insereDado(palavra126));
        Palavra palavra127 = new Palavra(128, "Parameter", "Parâmetro", "Característica /  Propriedade.", "Informação que define os limites ou as ações de alguma coisa, tais como uma variável, uma rotina ou um programa.", "6");
        System.out.println(crud.insereDado(palavra127));
        Palavra palavra128 = new Palavra(129, "Pointer", "Ponteiro", "Indicador.", "Haste variável, em um programa de computador, que contém o endereço para um item de dado ou instrução.", "6");
        System.out.println(crud.insereDado(palavra128));
        Palavra palavra129 = new Palavra(130, "Reference", "Referência", "Citação.", "Alusão a certa obra /  menção a um determinado fato ou trecho.", "6");
        System.out.println(crud.insereDado(palavra129));
        Palavra palavra130 = new Palavra(131, "Align", "Alinhar", "Ordernar /  Endireitar.", "Dispor(-se) em linha reta ou em fileira.", "6");
        System.out.println(crud.insereDado(palavra130));
        Palavra palavra131 = new Palavra(132, "Array", "Matriz", "Combinação.", "Arranjo de m.n elementos matemáticos dispostos num quadro retangular ou quadrado que comporta m linhas e n colunas.", "6");
        System.out.println(crud.insereDado(palavra131));
        Palavra palavra132 = new Palavra(133, "Type", "Tipo", "Forma /  Modelo.", "Objeto ou coisa que serve de modelo ou medida para produzir outro idêntico ou semelhante.", "6");
        System.out.println(crud.insereDado(palavra132));
        Palavra palavra133 = new Palavra(134, "Invalid", "Inválido", "Nulo.", "Que não é válido, que não apresenta os requisitos necessários para ter valor legal.", "6");
        System.out.println(crud.insereDado(palavra133));
        Palavra palavra134 = new Palavra(135, "Length", "Comprimento", "Extensão.", "Extensão de algo (como um vetor) considerado de uma extremidade à outra.", "6");
        System.out.println(crud.insereDado(palavra134));
        Palavra palavra135 = new Palavra(136, "Set", "Definir", "Determinar.", "Estabelecer com precisão.", "6");
        System.out.println(crud.insereDado(palavra135));
        Palavra palavra136 = new Palavra(137, "For", "Para", " ", "Indica finalidade.", "6");
        System.out.println(crud.insereDado(palavra136));
        Palavra palavra137 = new Palavra(138, "Return", "Retornar", "Voltar /  Devolver.", "Ir ou vir novamente.", "6");
        System.out.println(crud.insereDado(palavra137));
        Palavra palavra138 = new Palavra(139, "Wireless", "Sem fio", " ", "Termo utilizado para denominar uma rede de computadores sem a necessidade do uso de cabos, funcionando por meio de equipamentos que usam radiofrequência, comunicação via ondas de rádio, ou comunicação via infravermelho.", "7");
        System.out.println(crud.insereDado(palavra138));
        Palavra palavra139 = new Palavra(140, "Switch", "Switch", "Escolha.", "Equipamento utilizado para extensão física dos pontos de rede.", "7");
        System.out.println(crud.insereDado(palavra139));
        Palavra palavra140 = new Palavra(141, "Bridge", "Ponte", "Ligação /  Elo.", "Equipamento que funciona exatamente como uma ponte, pois possui a capacidade de interligar duas ou mais redes, reduzindo o tráfego entre segmentos de redes e convertendo diferentes padrões de redes.", "7");
        System.out.println(crud.insereDado(palavra140));
        Palavra palavra141 = new Palavra(142, "Adress", "Endereço", " ", "O número ou nome que identifica inconfundivelmente um registro, uma posição ou um dispositivo de memória.", "7");
        System.out.println(crud.insereDado(palavra141));
        Palavra palavra142 = new Palavra(143, "Network", "Rede", " ", "Sistema interligado de computadores, para comunicação e troca de dados.", "7");
        System.out.println(crud.insereDado(palavra142));
        Palavra palavra143 = new Palavra(144, "Router", "Roteador", " ", "Equipamento usado para conectar diferentes redes de computadores entre si.", "7");
        System.out.println(crud.insereDado(palavra143));
        Palavra palavra144 = new Palavra(145, "Frequency", "Frequência", "Regularidade.", "Repetição periódica ou costumeira de algo.", "7");
        System.out.println(crud.insereDado(palavra144));
        Palavra palavra145 = new Palavra(146, "Channel", "Canal", " ", "Faixa de frequência de ondas utilizada por algum aparelho.", "7");
        System.out.println(crud.insereDado(palavra145));
        Palavra palavra146 = new Palavra(147, "Application", "Aplicação", " ", " ", "7");
        System.out.println(crud.insereDado(palavra146));
        Palavra palavra147 = new Palavra(148, "Physical", "Físico", "Material /  Concreto.", " ", "7");
        System.out.println(crud.insereDado(palavra147));
        Palavra palavra148 = new Palavra(149, "Host", "Hospedeiro", " ", " ", "7");
        System.out.println(crud.insereDado(palavra148));
        Palavra palavra149 = new Palavra(150, "Frame", "Quadro", " ", " ", "7");
        System.out.println(crud.insereDado(palavra149));
        Palavra palavra150 = new Palavra(151, "Packet", "Pacote", " ", " ", "7");
        System.out.println(crud.insereDado(palavra150));
        Palavra palavra151 = new Palavra(152, "Layer", "Camada", " ", " ", "7");
        System.out.println(crud.insereDado(palavra151));
        Palavra palavra152 = new Palavra(153, "Size", "Tamanho/largura", "Grandeza.", " ", "7");
        System.out.println(crud.insereDado(palavra152));
        Palavra palavra153 = new Palavra(154, "Mask", "Máscara", "Fachada /  Aparência.", "Símbolo utilizado na formação de palavras-filtro, que representa um ou mais caracteres que ocupariam a mesma posição relativa no interior da palavra ou expressão /  caractere curinga.", "7");
        System.out.println(crud.insereDado(palavra153));
        Palavra palavra154 = new Palavra(155, "Defaut", "Original", "Inicial /  Padrão.", "Que provém de ou constitui a origem, o início.", "7");
        System.out.println(crud.insereDado(palavra154));
        Palavra palavra155 = new Palavra(156, "Gateway", "Porta", "Acesso.", "Ponto físico (hardware) ou lógico (software), no qual podem ser feitas conexões, ou seja, um canal através do qual os dados são transferidos entre um dispositivo de entrada e o processador ou entre o processador e um dispositivo de saída.", "7");
        System.out.println(crud.insereDado(palavra155));
        Palavra palavra156 = new Palavra(157, "Protocol", "Protocolo", "Formalidade.", "Característica do que segue normas rígidas de procedimento.", "7");
        System.out.println(crud.insereDado(palavra156));
        Palavra palavra157 = new Palavra(158, "Configuration", "Configuração", "Forma /  Formato.", "Arranjo de elementos interligados para operar como um todo ou um sistema.", "7");
        System.out.println(crud.insereDado(palavra157));
        Palavra palavra158 = new Palavra(159, "Dynamic", "Dinâmico", "Movimentado.", "Que se modifica continuamente, que evolui /  que pressupõe movimento.", "7");
        System.out.println(crud.insereDado(palavra158));
        Palavra palavra159 = new Palavra(160, "Server", "Servidor", " ", "Computador utilizado numa rede para proporcionar algum tipo de serviço (como acesso a arquivos ou a periféricos compartilhados) aos demais componentes da rede.", "7");
        System.out.println(crud.insereDado(palavra159));
        Palavra palavra160 = new Palavra(161, "System", "Sistema", "Conjunto /  Programa.", "Conjunto de programas que desempenham funções específicas.", "7");
        System.out.println(crud.insereDado(palavra160));
        Palavra palavra161 = new Palavra(162, "Setting", "Configuração", "Ajuste.", "Arranjo de elementos interligados para operar como um todo ou um sistema.", "7");
        System.out.println(crud.insereDado(palavra161));
        Palavra palavra162 = new Palavra(163, "Account", "Conta", " ", "Em uma rede ou sistema on-line, registro do nome, da senha e dos direitos de acesso de um usuário a essa rede ou sistema.", "7");
        System.out.println(crud.insereDado(palavra162));
        Palavra palavra163 = new Palavra(164, "Username", "Nome do Usuário", " ", "Identificação do usuário para acessar uma rede de computadores ou um determinado serviço na internet.", "7");
        System.out.println(crud.insereDado(palavra163));
        Palavra palavra164 = new Palavra(165, "Firewall", "Firewall", " ", "Dispositivo de segurança da rede que monitora o tráfego de rede de entrada e saída e decide permitir ou bloquear tráfegos específicos de acordo com um conjunto definido de regras de segurança.", "7");
        System.out.println(crud.insereDado(palavra164));
        Palavra palavra165 = new Palavra(166, "Select", "Selecionar", "Escolher.", "Fazer seleção ou escolha de.", "1");
        System.out.println(crud.insereDado(palavra165));
        Palavra palavra166 = new Palavra(167, "Insert", "Inserir", "Adicionar.", "Introduzir-se e ficar firme.", "1");
        System.out.println(crud.insereDado(palavra166));
        Palavra palavra167 = new Palavra(168, "From", "De", "Origem /  Fonte.", "Indica a origem ou procedência de alguém ou de algo.", "1");
        System.out.println(crud.insereDado(palavra167));
        Palavra palavra168 = new Palavra(169, "Where", "Onde", " ", "Em que lugar, em qual lugar.", "1");
        System.out.println(crud.insereDado(palavra168));
        Palavra palavra169 = new Palavra(170, "Order by", "Ordenar por", "Organizar.", "Dispor organizadamente pessoas ou coisas.", "1");
        System.out.println(crud.insereDado(palavra169));
        Palavra palavra170 = new Palavra(171, "Group by", "Agrupar por", "Reunir.", "Organizar em grupo mediante determinado critério.", "1");
        System.out.println(crud.insereDado(palavra170));
        Palavra palavra171 = new Palavra(172, "All", "Tudo", "Total.", "A totalidade dos seres e das coisas.", "1");
        System.out.println(crud.insereDado(palavra171));
        Palavra palavra172 = new Palavra(173, "Distinct", "Distinto", "Diferente.", "Que se diferencia dos demais.", "1");
        System.out.println(crud.insereDado(palavra172));
        Palavra palavra173 = new Palavra(174, "Top", "Cima", "Alto /  Topo.", "A parte superior de alguma coisa.", "1");
        System.out.println(crud.insereDado(palavra173));
        Palavra palavra174 = new Palavra(175, "As", "Como", "Que nem /  Tal como.", "Da mesma maneira que.", "1");
        System.out.println(crud.insereDado(palavra174));
        Palavra palavra175 = new Palavra(176, "Count", "Contagem", "Somar /  Calcular.", "Ação ou operação de contar.", "1");
        System.out.println(crud.insereDado(palavra175));
        Palavra palavra176 = new Palavra(177, "Have", "Ter", "Possuir /  Haver.", "Estar na posse de.", "1");
        System.out.println(crud.insereDado(palavra176));
        Palavra palavra177 = new Palavra(178, "Any", "Qualquer", "Qualquer /  Um.", "Designativo de pessoa, objeto, lugar ou tempo indeterminado, transmitindo a ideia de ?não importa qual.", "1");
        System.out.println(crud.insereDado(palavra177));
        Palavra palavra178 = new Palavra(179, "Some", "Alguns", "Bastantes /  Vários.", " ", "1");
        System.out.println(crud.insereDado(palavra178));
        Palavra palavra179 = new Palavra(180, "On", "Em", "Nele /  Sobre.", "Expressa lugar ou situação.", "1");
        System.out.println(crud.insereDado(palavra179));
        Palavra palavra180 = new Palavra(181, "Like", "Como", " ", "Da mesma maneira que.", "1");
        System.out.println(crud.insereDado(palavra180));
        Palavra palavra181 = new Palavra(182, "Between", "Entre", "No meio de /  Cercado por.", "Expressa a relação de lugar no espaço que separa duas coisas.", "1");
        System.out.println(crud.insereDado(palavra181));
        Palavra palavra182 = new Palavra(183, "Join", "Juntar", "Unir /  Reunir /  Ligar.", "Unir uma coisa a outra.", "1");
        System.out.println(crud.insereDado(palavra182));
        Palavra palavra183 = new Palavra(184, "Time", "Tempo", "Prazo /  Duração /  Período.", "Período de momentos, de horas, de dias, de semanas, de meses, de anos etc. no qual os eventos se sucedem, dando-se a noção de presente, passado e futuro.", "1");
        System.out.println(crud.insereDado(palavra183));
        Palavra palavra184 = new Palavra(185, "Create", "Criar", "Produzir /  Inventar.", "Dar existência.", "1");
        System.out.println(crud.insereDado(palavra184));
        Palavra palavra185 = new Palavra(186, "Table", "Tabela", "Lista.", "Lista de fatos e/ou números, arrumados numa ordem especial, geralmente em linhas e colunas.", "1");
        System.out.println(crud.insereDado(palavra185));
        Palavra palavra186 = new Palavra(187, "Union", "União", "Junção /  Fusão.", "Conjunção ou justaposição de dois ou mais seres, coisas etc.", "1");
        System.out.println(crud.insereDado(palavra186));
        Palavra palavra187 = new Palavra(188, "Database", "Banco de dados", " ", "Agrupamento de informações que se relacionam e tratam de um mesmo assunto.", "1");
        System.out.println(crud.insereDado(palavra187));
        Palavra palavra188 = new Palavra(189, "Signed", "Assinado", "Firmado.", "Que apresenta a assinatura de alguém.", "1");
        System.out.println(crud.insereDado(palavra188));
        Palavra palavra189 = new Palavra(190, "Unsigned", "Sem sinal", " ", " ", "1");
        System.out.println(crud.insereDado(palavra189));
        Palavra palavra190 = new Palavra(191, "Section", "Seção", "Repartição /  Parcela.", "Porção de um todo.", "8");
        System.out.println(crud.insereDado(palavra190));
        Palavra palavra191 = new Palavra(192, "Footer", "Rodapé", " ", "Artigo incluído na margem inferior da página de material impresso.", "8");
        System.out.println(crud.insereDado(palavra191));
        Palavra palavra192 = new Palavra(193, "Background", "Plano de fundo", " ", "Imagem (de qualquer natureza, desenhos, fotografias ou imagens digitais) que tem por função ilustrar e personalizar a tela principal de computadores, celulares, entre outros dispositivos.", "8");
        System.out.println(crud.insereDado(palavra192));
        Palavra palavra193 = new Palavra(194, "Widht", "Largura", " ", "Distância de lado a lado de uma superfície ou volume.", "8");
        System.out.println(crud.insereDado(palavra193));
        Palavra palavra194 = new Palavra(195, "Height", "Altura", "Tamanho.", "Distância entre o ponto mais baixo e o ponto mais alto de uma página.", "8");
        System.out.println(crud.insereDado(palavra194));
        Palavra palavra195 = new Palavra(196, "Title", "Título", "Denominação.", "A forma pela qual uma obra (um livro, um filme, um quadro etc.) é conhecida.", "8");
        System.out.println(crud.insereDado(palavra195));
        Palavra palavra196 = new Palavra(197, "Style", "Estilo", "Tipo /  Modo /  Forma.", "Padrão, variedade ou coleção de caracteres tipográficos com o mesmo desenho ou atributos e, por vezes, com o mesmo tamanho (corpo).", "8");
        System.out.println(crud.insereDado(palavra196));
        Palavra palavra197 = new Palavra(198, "Header", "Cabeçalho", " ", "O alto de uma página impressa ou o que aparece impresso nesse espaço.", "8");
        System.out.println(crud.insereDado(palavra197));
        Palavra palavra198 = new Palavra(199, "Figure", "Figura", "Imagem.", "Forma exterior de um corpo.", "8");
        System.out.println(crud.insereDado(palavra198));
        Palavra palavra199 = new Palavra(200, "Small", "Pequeno", "Diminuto /  Reduzido.", "Cujo tamanho é reduzido.", "8");
        System.out.println(crud.insereDado(palavra199));
        Palavra palavra200 = new Palavra(201, "Source", "Fonte", "Origem /  Procedência.", "Procedência de uma informação.", "8");
        System.out.println(crud.insereDado(palavra200));
        Palavra palavra201 = new Palavra(202, "Subtitle", "Subtítulo", " ", "Título secundário relacionado com o principal /  título posto por baixo de outro.", "8");
        System.out.println(crud.insereDado(palavra201));
        Palavra palavra202 = new Palavra(203, "Label", "Rótulo", "Legenda /  Etiqueta.", "Pequeno impresso, com formato variável, que se cola em frascos, garrafas, latas, caixas etc., para indicar o seu conteúdo.", "8");
        System.out.println(crud.insereDado(palavra202));
        Palavra palavra203 = new Palavra(204, "Button", "Botão", " ", "Pequeno círculo ou quadrado exibido numa caixa de diálogo que dispara uma ou mais ações, quando selecionado por um ponteiro ou teclado.", "8");
        System.out.println(crud.insereDado(palavra203));
        Palavra palavra204 = new Palavra(205, "Option", "Opção", "Alternativa /  Escolha", "Ato, faculdade ou resultado de optar.", "8");
        System.out.println(crud.insereDado(palavra204));
        Palavra palavra205 = new Palavra(206, "Progress", "Progresso", "Avanço /  Crescimento.", "Avanço de um processo.", "8");
        System.out.println(crud.insereDado(palavra205));
        Palavra palavra206 = new Palavra(207, "Repeat", "Repetir", "Refazer.", "Fazer algo novamente.", "8");
        System.out.println(crud.insereDado(palavra206));
        Palavra palavra207 = new Palavra(208, "Command", "Comando", "Controle.", "Pulso ou sinal reconhecido por um sistema operacional de computação que permite ao usuário iniciar, interromper ou finalizar uma ação, controlando a execução de um programa ou de alguma operação.", "8");
        System.out.println(crud.insereDado(palavra207));
        Palavra palavra208 = new Palavra(209, "Menu", "Menu", "Lista.", "Lista de opções ou entradas postas à disposição do usuário, que aparece no vídeo de um terminal de computador com as funções que este poderá, a seguir, realizar por meio de um programa ou de um software.", "8");
        System.out.println(crud.insereDado(palavra208));
        Palavra palavra209 = new Palavra(210, "Color", "Cor", "Pigmento.", " ", "8");
        System.out.println(crud.insereDado(palavra209));
        Palavra palavra210 = new Palavra(211, "Text", "Texto", "Conteúdo.", "Sequência de frases de um autor, em um documento, folheto, livro etc. /  redação original de uma obra escrita.", "8");
        System.out.println(crud.insereDado(palavra210));
        Palavra palavra211 = new Palavra(212, "Decoration", "Decoração", "Enfeite.", "Conjunto de técnicas para planejar e organizar espaços, combinando diversos elementos do ambiente de maneira estética e funcional de acordo com o fim a que se destina.", "8");
        System.out.println(crud.insereDado(palavra211));
        Palavra palavra212 = new Palavra(213, "Font", "Fonte", "Tipo.", "O que fornece informações sobre determinado assunto.", "8");
        System.out.println(crud.insereDado(palavra212));
        Palavra palavra213 = new Palavra(214, "Family", "Família", "Categoria /  Grupo.", "Grupo de coisas que apresentam propriedade ou características comuns.", "8");
        System.out.println(crud.insereDado(palavra213));
        Palavra palavra214 = new Palavra(215, "Position", "Posição", "Localização /  Ponto /  Lugar.", "Maneira de um corpo ocupar um espaço.", "8");
        System.out.println(crud.insereDado(palavra214));
        Palavra palavra215 = new Palavra(216, "Circle", "Círculo", "Circunferência.", "Figura plana limitada por uma linha curva cujos pontos estão sempre à mesma distância de um centro.", "8");
        System.out.println(crud.insereDado(palavra215));
        Palavra palavra216 = new Palavra(217, "Lower", "Inferior", "Abaixo.", "Que está abaixo ou para baixo.", "8");
        System.out.println(crud.insereDado(palavra216));
        Palavra palavra217 = new Palavra(218, "Upper", "Superior", "Acima.", "Que está situado mais alto /  que está acima de outro.", "8");
        System.out.println(crud.insereDado(palavra217));
        Palavra palavra218 = new Palavra(219, "Border", "Borda", "Beirada.", "Extremidade limite de uma superfície.", "8");
        System.out.println(crud.insereDado(palavra218));
        Palavra palavra219 = new Palavra(220, "Browser", "Navegador", "Margem.", "Aplicativo ou parte de aplicativo que permite a um usuário acessar e pesquisar facilmente páginas de hipertexto, numa base de dados e principalmente pelos links e outros recursos da internet.", "8");
        System.out.println(crud.insereDado(palavra219));
        Palavra palavra220 = new Palavra(221, "Download", "Baixar", "Tranferir /  Copiar.", "Transferir, através de computadores em rede, dados ou arquivos de uma máquina para outra.", "8");
        System.out.println(crud.insereDado(palavra220));
        Palavra palavra221 = new Palavra(222, "Upload", "Enviar", "Transmitir.", "Fazer remessa de algo para certo endereço.", "8");
        System.out.println(crud.insereDado(palavra221));
        Palavra palavra222 = new Palavra(223, "Home page", "Página inicial", " ", "É a página de entrada de um site da internet. Compreende uma apresentação do site e de todo seu conteúdo", "8");
        System.out.println(crud.insereDado(palavra222));
        Palavra palavra223 = new Palavra(224, "Cookie", "Cookies", " ", "Utilizados por sites principalmente para identificar e armazenar informações sobre os visitantes. Eles são pequenos arquivos de texto que ficam gravados no computador do internauta e podem ser recuperados pelo site que o enviou durante a navegação.", "8");
        System.out.println(crud.insereDado(palavra223));


    }

}
